import { readFile, readdir, writeFile } from "node:fs/promises";

const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
const files = {};
const bundleOrder = [
  "core/symbols.js",
  "core/rules.js",
  "ai/schemas.js",
  "ai/prompts.js",
  "ai/model-manifest.js",
  "ai/adapters.js",
  "ai/router.js",
  "core/narrator.js",
  "core/storage.js",
  "app.js"
];

for (const name of await listSourceFiles("src")) {
  if (name === "app.js") {
    files[name] = await buildAppBundle();
  } else {
    files[name] = await readFile(`src/${name}`, "utf8");
  }
}

files["README.md"] = await readFile("README.md", "utf8");
for (const name of await listSourceFiles("docs")) {
  files[`docs/${name}`] = await readFile(`docs/${name}`, "utf8");
}

const appPackage = { manifest, files };
await writeFile("package.sapp.json", `${JSON.stringify(appPackage, null, 2)}\n`);
console.log(`Wrote package.sapp.json for ${manifest.name} ${manifest.version}.`);

async function listSourceFiles(dir, prefix = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const paths = [];
  for (const entry of entries) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      paths.push(...await listSourceFiles(`${dir}/${entry.name}`, relative));
    } else {
      paths.push(relative);
    }
  }
  return paths.sort();
}

async function buildAppBundle() {
  const chunks = [];
  for (const name of bundleOrder) {
    const source = await readFile(`src/${name}`, "utf8");
    chunks.push(`// ---- ${name} ----\n${toBundleChunk(source)}`);
  }
  return [
    "// Rogue Shell packaged bundle.",
    "// Generated by scripts/build-package.mjs so Shellex srcdoc iframes do not need relative ES module imports.",
    ...chunks
  ].join("\n\n");
}

function toBundleChunk(source) {
  return source
    .replace(/^\s*import\s+[^;]+;\s*$/gm, "")
    .replace(/^\s*export\s+(?=(const|let|var|function|class)\s)/gm, "");
}
